export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';

export const PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST';
export const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS';
export const PAY_ORDER_FAILED = 'PAY_ORDER_FAILED';

export const GET_ORDER_LIST_REQUEST = 'GET_ORDER_LIST_REQUEST';
export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS'
export const GET_ORDER_LIST_FAILED = 'GET_ORDER_LIST_FAILED';

export const CLEAR_ORDERS = 'CLEAR_ORDERS';
export const CLEAR_PAY_ORDER = 'CLEAR_PAY_ORDER';