export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const SIGN_OUT = 'SIGN_OUT';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_REQUEST_SUCCESS = 'USER_DETAILS_REQUEST_SUCCESS';
export const USER_DETAILS_REQUEST_FAILED = 'USER_DETAILS_REQUEST_FAILED';

export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS_REQUEST';
export const UPDATE_USER_DETAILS_REQUEST_SUCCESS = 'UPDATE_USER_DETAILS_REQUEST_SUCCESS';
export const UPDATE_USER_DETAILS_REQUEST_FAILED = 'UPDATE_USER_DETAILS_REQUEST_FAILED'; 
export const USER_DETAILS_CLEAR_ERRORS = 'USER_DETAILS_CLEAR_ERRORS';
export const USER_DETAILS_CLEAR_MESSAGE = 'USER_DETAILS_CLEAR_MESSAGE';